from combustivel import Combustivel

bomba1 = Combustivel('alcool')
bomba1.quantidadeCombustivel()
bomba1.adicionarCombustivel(12.34)
bomba1.quantidadeCombustivel()
bomba1.adicionarCombustivel(43.21)
bomba1.quantidadeCombustivel()
bomba1.abastecerPorValor(50.00)
bomba1.quantidadeCombustivel()
bomba1.abastecerPorValor(5.54)
bomba1.quantidadeCombustivel()
bomba1.adicionarCombustivel(100.00)
bomba1.quantidadeCombustivel()
bomba1.atualizarValorLitro(2.00)
bomba1.abastecerPorLitros(80)
bomba1.quantidadeCombustivel()
bomba1.abastecerPorValor(5.54)
bomba1.atualizarValorLitro(2.52)
bomba1.abastecerPorValor(5.54)
bomba1.atualizarValorLitro(2.99)
bomba1.abastecerPorValor(5.54)
bomba1.mudarBombaCombustivel()

print()
print('########################################')
print()
bomba2 = Combustivel('gasolina')
bomba2.quantidadeCombustivel()
bomba2.adicionarCombustivel(12.34)
bomba2.adicionarCombustivel(12.34)
bomba2.quantidadeCombustivel()
bomba2.abastecerPorValor(10.00)
bomba2.atualizarValorLitro(4.69)
bomba2.atualizarValorLitro(4.68)
bomba2.abastecerPorValor(10.00)
bomba2.abastecerPorValor(10.00)
bomba2.abastecerPorValor(10.00)
bomba2.adicionarCombustivel(12.34)
bomba2.adicionarCombustivel(12.34)
bomba2.adicionarCombustivel(12.34)
bomba2.adicionarCombustivel(12.34)
bomba2.quantidadeCombustivel()
bomba2.quantidadeCombustivel()
bomba2.quantidadeCombustivel()
bomba2.quantidadeCombustivel()
bomba2.quantidadeCombustivel()
bomba2.atualizarValorLitro(4.68)
bomba2.abastecerPorLitros(50)
bomba2.quantidadeCombustivel()
bomba2.abastecerPorLitros(50)
bomba2.mudarBombaCombustivel()