from classes.funcionalidade import theFunctions

agenda1 = theFunctions()
agenda1.addContact('Ricardo', '951540122')
agenda1.addContact('Wilson', '1951540122')
agenda1.addContact('Pereira', '12345678')
agenda1.checkAllContacts()
agenda1.checkContact('951540122')
agenda1.checkContact('Wilson')
agenda1.checkContact('Carlos')
agenda1.checkContact('Carlos')
agenda1.checkContact('Pereira')
agenda1.checkContact('Carlos')
agenda1.ligar('Ricardo')
agenda1.ligar('Wilson')
agenda1.ligar('Wilson')
agenda1.ligar('Wilson')
agenda1.desligar()
agenda1.ligar('Wilson')
agenda1.desligar()
agenda1.desligar()
agenda1.desligar()
agenda1.ligar('Ricardo')
agenda1.addContact('Pereira', '12345678')
agenda1.checkAllContacts()
